# Generated by Django 2.2 on 2021-01-28 15:46

import classes.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0002_auto_20210128_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_id', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=250)),
                ('position', models.PositiveSmallIntegerField(verbose_name='Lecture Number')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to=classes.models.lesson_files, verbose_name='Video')),
                ('notes', models.FileField(blank=True, null=True, upload_to=classes.models.lesson_files, verbose_name='Notes')),
                ('ppt', models.FileField(blank=True, null=True, upload_to=classes.models.lesson_files, verbose_name='Presentation')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.Branch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.Semester')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to=classes.models.subject_image, verbose_name='Subject Image')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.Branch')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='classes.Semester')),
            ],
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='semester',
        ),
        migrations.DeleteModel(
            name='Lessons',
        ),
        migrations.DeleteModel(
            name='Subjects',
        ),
        migrations.AddField(
            model_name='lesson',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='classes.Subject'),
        ),
    ]
