# Generated by Django 2.2 on 2021-02-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_auto_20210204_0429'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='submission',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
