# Generated by Django 2.2 on 2021-02-15 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_assignment_last_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='last_date',
            field=models.DateTimeField(),
        ),
    ]
